services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: datapulse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    depends_on:
      - db
    restart: on-failure
    environment:
      - DJANGO_DB_HOST=db
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data:
